# Generated by Django 5.2.14 on 2026-05-27 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('hora_inicio', models.TextField()),
                ('hora_fim', models.TextField()),
                ('status', models.TextField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa')),
            ],
            options={
                'db_table': 'reservas',
                'ordering': ['data', 'hora_inicio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'db_table': 'salas',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
